### ISSUE TITLE
Crowd Grenades In Riot Launchers Don't Create Capsaicin Smoke

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#11018]
### Labels

[BUG]

### Description

Putting a crowd dispersal grenade in a riot launcher, then using it will not create a cloud of capsaicin.

### Steps to reproduce

1. Get an empty riot launcher
2. Put a crowd grenade in it
3. Fire the grenade
4. Notice no capsaicin smoke

### Expected Behavior

For the launched grenade to create chem smoke

**Comment by NightmareChamillian** [comment]
IIRC smoke grenades as a whole are broken

**Comment by MetricDuck** [comment]
Seems to work for me right now, might have been fixed?

**Comment by FlameArrow57** [comment]
Still an issue, it has to hit a wall I think, was working when hitting objects

**Comment by pgmzeta** [comment]
maybe an interaction with the newer liquid-splashing-off-walls behavior?
