### ISSUE TITLE
Blueprint Maker works on goon2 but not goon1

### ISSUE THREAD

**Issue by Jak27** [goonstation/goonstation#6967]
### Labels

[BUG]

### Description

I can save and print blueprints using the blueprint maker on goon2, but it doesn't save correctly on goon1

### Steps to reproduce

1. log into goon1
2. get a blueprint maker
3. set a blueprint name, select some tiles to save into a blueprint
4. hit save
5. try to print blueprint
6. "No blueprints found for user."

### Expected Behavior

Should have printed a blueprint of the tiles I saved

**Comment by MRLinew** [comment]
About a month ago I also noticed my ABCU saves were wiped on goon1.

**Comment by ZeWaka** [comment]
fixed

**Comment by Jak27** [comment]
> fixed

Just tried this again on goon1, I am still getting the issue. I don't think this is fixed.

**Comment by ZeWaka** [comment]
Was fixed when I tried it
